### ISSUE TITLE
关于Cilium新版本安装的问题

### ISSUE THREAD

**Issue by mxdblcf** [nevermosby/K8S-CNI-Cilium-Tutorial#1]
请问你安装Cilium的时候有没有遇到DNS路径找不到的问题，我安装Cilium1.10完，dns完全不能用了，ping百度也不行，应该是安装失败了，环境是k8s1.22 虚拟机集群

**Comment by nevermosby** [comment]
@mxdblcf 建议的排查思路：
1. dns相关问题一般是coredns组件引起的，可以首先看看coredns日志，是否有报错。
2. 在安装Cilium等k8s网络插件时，会重启coredns，因此也有可能会导致coredns异常，可以看看cilium operator/agent日志是否有异常
3. 看看kubelet状态和日志，我最近试过了rhel8 + k8s 1.22 + cilium 1.10.3安装组合，一度卡在kubelet有问题，后面解决掉后就运行ok了。

希望能帮助到你。

**Comment by mxdblcf** [comment]
thinks, i try
